paths:
  assembly_dir: "data/processed" #Add the dir for the assemblies
  int_bin_dir: "data/processed/int_bins"
  refined_bin_dir: "data/processed/refined_bins"
  final_mag_dir: "data/processed/final_bins"

programs:
  maxbin2: "path/to/maxbin2"
  metabat2: "path/to/metabat2"
  concoct: "path/to/concoct"
